/* Generated By AI Start (Cursor) */
import { defineConfig } from 'vite';
import vue from '@vitejs/plugin-vue';
import { fileURLToPath, URL } from 'node:url';

export default defineConfig({
  base: '/myresume/',
  plugins: [vue()],
  resolve: {
    alias: {
      '@': fileURLToPath(new URL('./src', import.meta.url))
    }
  },
  build: {
    outDir: 'dist',
    assetsDir: 'static'
  },
  server: {
    port: 8080,
    open: '/myresume/'
  }
});
/* Generated By AI End (Cursor) */
