/* Generated By AI Start (Cursor) */
import { createRouter, createWebHistory } from 'vue-router';

const PartOne = () => import('@/components/PartOne.vue');
const PartTwo = () => import('@/components/PartTwo.vue');
const PartThree = () => import('@/components/PartThree.vue');
const PartFour = () => import('@/components/PartFour.vue');
const PartFive = () => import('@/components/PartFive.vue');
const PartSix = () => import('@/components/PartSix.vue');
const PartSeven = () => import('@/components/PartSeven.vue');

export default createRouter({
  history: createWebHistory(import.meta.env.BASE_URL),
  routes: [
    {
      path: '/',
      components: {
        PartOne,
        PartTwo,
        PartThree,
        PartFour,
        PartFive,
        PartSix,
        PartSeven
      }
    }
  ]
});
/* Generated By AI End (Cursor) */
