<template>
  <!-- Generated By AI Start (Cursor) -->
  <transition name="idle-wave-fade">
    <div v-if="visible" class="idle-wave-overlay" aria-hidden="true">
      <div class="idle-wave-beam"></div>
    </div>
  </transition>
  <!-- Generated By AI End (Cursor) -->
</template>

<script>
/* Generated By AI Start (Cursor) */
export default {
  name: 'IdleWaveOverlay',
  props: {
    visible: {
      type: Boolean,
      default: false
    }
  }
};
/* Generated By AI End (Cursor) */
</script>

<style scoped>
/* Generated By AI Start (Cursor) */
.idle-wave-overlay {
  position: fixed;
  inset: 0;
  z-index: 9999;
  pointer-events: none;
  overflow: hidden;
}

.idle-wave-beam {
  position: absolute;
  top: 0;
  left: 0;
  width: 1px;
  height: 100%;
  background: linear-gradient(
    to bottom,
    rgba(56, 189, 248, 0) 0%,
    rgba(56, 189, 248, 0.22) 20%,
    rgba(56, 189, 248, 0.38) 50%,
    rgba(56, 189, 248, 0.22) 80%,
    rgba(56, 189, 248, 0) 100%
  );
  box-shadow: 0 0 8px rgba(56, 189, 248, 0.18);
  opacity: 0.45;
  animation: idle-beam-sweep 5.5s linear infinite;
}

.idle-wave-fade-enter-active,
.idle-wave-fade-leave-active {
  transition: opacity 0.6s ease;
}

.idle-wave-fade-enter,
.idle-wave-fade-leave-to {
  opacity: 0;
}

@keyframes idle-beam-sweep {
  0% {
    transform: translateX(-8px);
    opacity: 0;
  }
  8% {
    opacity: 0.45;
  }
  92% {
    opacity: 0.45;
  }
  100% {
    transform: translateX(calc(100vw + 8px));
    opacity: 0;
  }
}

@media (prefers-reduced-motion: reduce) {
  .idle-wave-beam {
    animation: none !important;
  }
}
/* Generated By AI End (Cursor) */
</style>
