<template>
  <!-- Generated By AI Start (Cursor) -->
  <div class="resume-card resume-stagger-2 part-two-wrap">
    <div ref="chartRef" class="resume-chart part-two"></div>
  </div>
  <!-- Generated By AI End (Cursor) -->
</template>

<script>
/* Generated By AI Start (Cursor) */
import echarts from '@/utils/echarts';

export default {
  name: "partTwo",
  data() {
    return {
      chart: null
    };
  },
  mounted() {
    this.drawECharts();
    window.addEventListener('resize', this.handleResize);
  },
  beforeUnmount() {
    window.removeEventListener('resize', this.handleResize);
    if (this.chart) {
      this.chart.dispose();
    }
  },
  methods: {
    handleResize() {
      if (this.chart) {
        this.chart.resize();
      }
    },
    drawECharts() {
      this.chart = echarts.init(this.$refs.chartRef);

      const workCities = [
        { name: "成都", value: ["104.06", "30.67", "15"] },
        { name: "武汉", value: ["110.35", "20.02", "4"] },
        { name: "广州", value: ["113.23", "23.16", "4"] }
      ];

      const workProvinces = [
        { name: "四川" },
        { name: "湖北" },
        { name: "广东" }
      ];

      this.chart.setOption({
        title: {
          text: "职业发展足迹",
          subtext: "工作城市分布",
          textStyle: { color: "#38bdf8", fontSize: 14, fontWeight: 600 },
          subtextStyle: { color: "#94a3b8", fontSize: 11 },
          left: "center",
          top: 4
        },
        tooltip: {
          trigger: "item",
          backgroundColor: "rgba(15, 23, 42, 0.92)",
          borderColor: "rgba(56, 189, 248, 0.4)",
          textStyle: { color: "#f1f5f9" },
          formatter(params) {
            if (params.value && params.value[2]) {
              return params.name + " · 工作经历 " + params.value[2];
            }
            return params.name || "暂无记录";
          }
        },
        geo: { map: "china", roam: false },
        series: [
          {
            name: "工作城市",
            type: "effectScatter",
            coordinateSystem: "geo",
            symbolSize(val) { return val[2] * 1.2; },
            showEffectOn: "render",
            rippleEffect: { brushType: "stroke", scale: 3, period: 4 },
            label: {
              formatter: "{b}",
              position: "right",
              show: true,
              color: "#f1f5f9",
              fontSize: 11
            },
            itemStyle: {
              color: "#38bdf8",
              shadowBlur: 16,
              shadowColor: "rgba(56, 189, 248, 0.6)"
            },
            zlevel: 1,
            data: workCities
          },
          {
            name: "工作省份",
            type: "map",
            map: "china",
            roam: false,
            label: { show: false },
            itemStyle: {
              borderWidth: 0.5,
              borderColor: "rgba(56, 189, 248, 0.3)",
              areaColor: "rgba(30, 58, 95, 0.85)"
            },
            emphasis: {
              label: { show: false },
              itemStyle: {
                borderWidth: 1.5,
                borderColor: "#38bdf8",
                areaColor: "rgba(56, 189, 248, 0.35)"
              }
            },
            data: workProvinces
          }
        ]
      });
    }
  }
};
/* Generated By AI End (Cursor) */
</script>

<style scoped>
/* Generated By AI Start (Cursor) */
.part-two-wrap {
  height: 100%;
}
/* Generated By AI End (Cursor) */
</style>
