<template>
  <!-- Generated By AI Start (Cursor) -->
  <div :class="['resume-card', 'resume-stagger-7', partSeven]">
    <div class="resume-card-inner">
      <h3 class="resume-section-title">
        <ResumeIcon name="target" :size="18" />
        求职意向
      </h3>
      <ResumeScroll>
        <div class="resume-info-row">
          <ResumeIcon name="briefcase" :size="14" />
          <span>期望职位：Web 前端开发</span>
        </div>
        <div class="resume-info-row">
          <ResumeIcon name="code" :size="14" />
          <span>核心技能：Vue3 全家桶</span>
        </div>
        <div class="resume-info-row">
          <ResumeIcon name="mapPin" :size="14" />
          <span>目标城市：成都</span>
        </div>
        <div class="resume-info-row">
          <ResumeIcon name="star" :size="14" />
          <span>入职时间：随时入职</span>
        </div>

        <div class="self-eval">
          <h4 class="eval-title">
            <ResumeIcon name="star" :size="14" />
            自我评价
          </h4>
          <p class="resume-text-small">5 年专注 B 端前端开发，擅长使用 AI 辅助编程提升效率。对 Vue 生态保持热情，持续关注新工具与最佳实践，学习能力强，有计划有条理，执行力强。</p>
        </div>
      </ResumeScroll>
    </div>
  </div>
  <!-- Generated By AI End (Cursor) -->
</template>

<script>
/* Generated By AI Start (Cursor) */
import ResumeIcon from '@/components/ResumeIcon.vue';
import ResumeScroll from '@/components/ResumeScroll.vue';

export default {
  name: "partSeven",
  components: { ResumeIcon, ResumeScroll },
  data() {
    return {
      partSeven: "part-seven"
    };
  }
};
/* Generated By AI End (Cursor) */
</script>

<style scoped>
/* Generated By AI Start (Cursor) */
.self-eval {
  margin-top: 10px;
  padding-top: 10px;
  border-top: 1px solid rgba(56, 189, 248, 0.15);
}

.eval-title {
  display: flex;
  align-items: center;
  gap: 5px;
  font-size: 0.88em;
  color: var(--resume-primary, #38bdf8);
  margin-bottom: 6px;
}
/* Generated By AI End (Cursor) */
</style>
