<template>
  <!-- Generated By AI Start (Cursor) -->
  <div class="resume-card resume-stagger-4 part-four-wrap">
    <div ref="chartRef" class="resume-chart part-four"></div>
  </div>
  <!-- Generated By AI End (Cursor) -->
</template>

<script>
/* Generated By AI Start (Cursor) */
import echarts from '@/utils/echarts';

export default {
  name: "partFour",
  data() {
    return {
      chart: null
    };
  },
  mounted() {
    this.drawECharts();
    window.addEventListener('resize', this.handleResize);
  },
  beforeUnmount() {
    window.removeEventListener('resize', this.handleResize);
    if (this.chart) {
      this.chart.dispose();
    }
  },
  methods: {
    handleResize() {
      if (this.chart) {
        this.chart.resize();
      }
    },
    drawECharts() {
      this.chart = echarts.init(this.$refs.chartRef);

      this.chart.setOption({
        title: {
          text: "核心能力雷达",
          textStyle: { color: "#38bdf8", fontSize: 14, fontWeight: 600 },
          left: "center",
          top: 4
        },
        tooltip: {
          backgroundColor: "rgba(15, 23, 42, 0.92)",
          borderColor: "rgba(56, 189, 248, 0.4)",
          textStyle: { color: "#f1f5f9" }
        },
        radar: {
          center: ["50%", "54%"],
          radius: "58%",
          indicator: [
            { name: "Vue 生态", max: 100 },
            { name: "工程化", max: 100 },
            { name: "B 端业务", max: 100 },
            { name: "组件设计", max: 100 },
            { name: "AI 辅助", max: 100 },
            { name: "性能优化", max: 100 }
          ],
          axisName: { color: "#94a3b8", fontSize: 10 },
          splitArea: {
            areaStyle: {
              color: ["rgba(56, 189, 248, 0.04)", "rgba(56, 189, 248, 0.08)"]
            }
          },
          splitLine: { lineStyle: { color: "rgba(56, 189, 248, 0.15)" } },
          axisLine: { lineStyle: { color: "rgba(56, 189, 248, 0.25)" } }
        },
        series: [{
          type: "radar",
          animationDuration: 1200,
          animationEasing: "cubicOut",
          data: [{
            value: [92, 85, 90, 88, 82, 78],
            name: "能力值",
            areaStyle: {
              color: "rgba(56, 189, 248, 0.25)"
            },
            lineStyle: {
              color: "#38bdf8",
              width: 2
            },
            itemStyle: {
              color: "#38bdf8",
              borderColor: "#818cf8",
              borderWidth: 2
            }
          }]
        }]
      });
    }
  }
};
/* Generated By AI End (Cursor) */
</script>

<style scoped>
/* Generated By AI Start (Cursor) */
.part-four-wrap {
  height: 100%;
}
/* Generated By AI End (Cursor) */
</style>
