<template>
  <!-- Generated By AI Start (Cursor) -->
  <div :class="['resume-card', 'resume-stagger-5', partFive]">
    <div class="resume-card-inner">
      <h3 class="resume-section-title">
        <ResumeIcon name="briefcase" :size="18" />
        工作经历
      </h3>
      <ResumeScroll>
        <div class="resume-timeline-item">
          <p>
            <span class="resume-company">德特赛维技术有限公司</span>
            <span class="resume-date">| 2023.10 - 2026.06</span>
          </p>
          <p class="resume-text-small">岗位：前端开发 · ToB 项目</p>
          <p class="resume-text-small">&emsp;· 负责项目需求迭代，保障平台稳定运行</p>
          <p class="resume-text-small">&emsp;· 主导 Vue2 升级 Vue3，提升代码可维护性</p>
          <p class="resume-text-small">&emsp;· 从零搭建客户论坛、在线学习平台</p>
          <p class="resume-text-small">&emsp;· 搭建 Jenkins 自动化部署，提高部署效率</p>
        </div>

        <div class="resume-timeline-item">
          <p>
            <span class="resume-company">华雁智能科技股份有限公司</span>
            <span class="resume-date">| 2022.03 - 2023.06</span>
          </p>
          <p class="resume-text-small">岗位：前端开发 · 低代码平台</p>
          <p class="resume-text-small">&emsp;· 权限管理、主题导航、工作台等核心模块开发</p>
          <p class="resume-text-small">&emsp;· 组件与平台交互，组件化改造，效率提升约 30%</p>
          <p class="resume-text-small">&emsp;· 项目发布基座开发及迭代维护</p>
        </div>

        <div class="resume-timeline-item">
          <p>
            <span class="resume-company">海南安迈云网络技术有限公司</span>
            <span class="resume-date">| 2020.06 - 2022.02</span>
          </p>
          <p class="resume-text-small">岗位：前端开发 · App / H5 / PC</p>
          <p class="resume-text-small">&emsp;· 负责 App、H5 及 PC 官网功能迭代与维护</p>
          <p class="resume-text-small">&emsp;· 独立负责电商后台（权限、订单、数据看板）</p>
        </div>
      </ResumeScroll>
    </div>
  </div>
  <!-- Generated By AI End (Cursor) -->
</template>

<script>
/* Generated By AI Start (Cursor) */
import ResumeIcon from '@/components/ResumeIcon.vue';
import ResumeScroll from '@/components/ResumeScroll.vue';

export default {
  name: "partFive",
  components: { ResumeIcon, ResumeScroll },
  data() {
    return {
      partFive: "part-five"
    };
  }
};
/* Generated By AI End (Cursor) */
</script>
