<template>
  <!-- Generated By AI Start (Cursor) -->
  <div :class="['resume-card', 'resume-stagger-6', partSix]">
    <div class="resume-card-inner">
      <h3 class="resume-section-title">
        <ResumeIcon name="cpu" :size="18" />
        专业技能
      </h3>
      <ResumeScroll>
        <div class="skill-group">
          <p class="skill-label"><ResumeIcon name="code" :size="13" /> 前端核心</p>
          <span class="resume-tag">HTML5</span>
          <span class="resume-tag">CSS3</span>
          <span class="resume-tag">JavaScript</span>
          <span class="resume-tag">ES6</span>
          <span class="resume-tag">响应式布局</span>
        </div>
        <div class="skill-group">
          <p class="skill-label"><ResumeIcon name="layers" :size="13" /> 框架生态</p>
          <span class="resume-tag">Vue3</span>
          <span class="resume-tag">Pinia</span>
          <span class="resume-tag">Vue Router</span>
          <span class="resume-tag">Vite</span>
          <!-- <span class="resume-tag">ElementUI</span> -->
        </div>
        <div class="skill-group">
          <p class="skill-label"><ResumeIcon name="zap" :size="13" /> AI & 工具</p>
          <span class="resume-tag">Cursor</span>
          <span class="resume-tag">OpenCode</span>
          <span class="resume-tag">Git / SVN</span>
          <span class="resume-tag">Canvas 动画</span>
        </div>
        <div class="skill-group">
          <p class="skill-label"><ResumeIcon name="tool" :size="13" /> 后端了解</p>
          <span class="resume-tag">Node.js</span>
          <span class="resume-tag">Express</span>
          <span class="resume-tag">Ajax / HTTP</span>
        </div>
      </ResumeScroll>
    </div>
  </div>
  <!-- Generated By AI End (Cursor) -->
</template>

<script>
/* Generated By AI Start (Cursor) */
import ResumeIcon from '@/components/ResumeIcon.vue';
import ResumeScroll from '@/components/ResumeScroll.vue';

export default {
  name: "partSix",
  components: { ResumeIcon, ResumeScroll },
  data() {
    return {
      partSix: "part-six"
    };
  }
};
/* Generated By AI End (Cursor) */
</script>

<style scoped>
/* Generated By AI Start (Cursor) */
.skill-group {
  margin-bottom: 10px;
}

.skill-label {
  display: flex;
  align-items: center;
  gap: 5px;
  font-size: 0.84em;
  font-weight: 600;
  color: var(--resume-primary, #38bdf8);
  margin-bottom: 4px;
}
/* Generated By AI End (Cursor) */
</style>
