<template>
  <!-- Generated By AI Start (Cursor) -->
  <div class="resume-card resume-stagger-3 part-three-wrap">
    <div ref="chartRef" class="resume-chart part-three"></div>
  </div>
  <!-- Generated By AI End (Cursor) -->
</template>

<script>
/* Generated By AI Start (Cursor) */
import echarts from '@/utils/echarts';

export default {
  name: "partThree",
  data() {
    return {
      chart: null
    };
  },
  mounted() {
    this.drawECharts();
    window.addEventListener('resize', this.handleResize);
  },
  beforeUnmount() {
    window.removeEventListener('resize', this.handleResize);
    if (this.chart) {
      this.chart.dispose();
    }
  },
  methods: {
    handleResize() {
      if (this.chart) {
        this.chart.resize();
      }
    },
    drawECharts() {
      this.chart = echarts.init(this.$refs.chartRef);

      this.chart.setOption({
        title: {
          text: "技能分布图",
          textStyle: { color: "#38bdf8", fontSize: 14, fontWeight: 600 },
          left: "center",
          top: 4
        },
        tooltip: {
          trigger: "item",
          backgroundColor: "rgba(15, 23, 42, 0.92)",
          borderColor: "rgba(56, 189, 248, 0.4)",
          textStyle: { color: "#f1f5f9" },
          formatter: "{a} <br/>{b} : {d}%"
        },
        legend: {
          left: "center",
          bottom: 0,
          itemWidth: 10,
          itemHeight: 10,
          textStyle: { color: "#94a3b8", fontSize: 10 },
          data: ["Vue3", "HTML/CSS/JS", "Node.js", "AI 工具", "Git/部署"]
        },
        series: [{
          name: "技能分布",
          type: "pie",
          radius: ["18%", "58%"],
          center: ["50%", "46%"],
          roseType: "area",
          animationType: "scale",
          animationEasing: "elasticOut",
          animationDelay(idx) { return idx * 80; },
          itemStyle: {
            borderRadius: 4,
            borderColor: "rgba(15, 23, 42, 0.8)",
            borderWidth: 2
          },
          label: {
            color: "#f1f5f9",
            fontSize: 10
          },
          data: [
            { value: 45, name: "Vue3" },
            { value: 25, name: "HTML/CSS/JS" },
            { value: 10, name: "Node.js" },
            { value: 10, name: "AI 工具" },
            { value: 10, name: "Git/部署" }
          ]
        }],
        color: ["#38bdf8", "#818cf8", "#22d3ee", "#6366f1", "#a78bfa", "#06b6d4"]
      });
    }
  }
};
/* Generated By AI End (Cursor) */
</script>

<style scoped>
/* Generated By AI Start (Cursor) */
.part-three-wrap {
  height: 100%;
}
/* Generated By AI End (Cursor) */
</style>
