<template>
  <!-- Generated By AI Start (Cursor) -->
  <div class="resume-card resume-stagger-1 part-one">
    <div class="resume-card-inner">
      <div class="resume-profile-header">
        <div class="resume-avatar-wrap">
          <img class="resume-avatar" :src="headImage" alt="宋旭缘头像">
        </div>
        <h3 class="resume-section-title">
          <ResumeIcon name="user" :size="18" />
          基本信息
        </h3>
      </div>
      <ResumeScroll>
        <div class="resume-info-row">
          <ResumeIcon name="user" :size="14" />
          <span>姓名：宋旭缘</span>
        </div>
        <div class="resume-info-row">
          <ResumeIcon name="briefcase" :size="14" />
          <span>工作年限：5 年</span>
        </div>
        <div class="resume-info-row">
          <ResumeIcon name="graduation" :size="14" />
          <span>学历：本科 · 成都信息工程大学</span>
        </div>
        <div class="resume-info-row">
          <ResumeIcon name="phone" :size="14" />
          <span>电话：18096295110</span>
        </div>
        <div class="resume-info-row">
          <ResumeIcon name="mail" :size="14" />
          <span>邮箱：541046145@qq.com</span>
        </div>
        <div class="resume-info-row">
          <ResumeIcon name="mapPin" :size="14" />
          <span>所在城市：成都市</span>
        </div>
        <div class="resume-info-row">
          <ResumeIcon name="globe" :size="14" />
          <span>博客：<a class="resume-link" href="http://songxuy.github.io" target="_blank" rel="noopener">songxuy.github.io</a></span>
        </div>
        <!-- <div class="resume-info-row">
          <ResumeIcon name="github" :size="14" />
          <span>GitHub：<a class="resume-link" href="https://github.com/songxuy" target="_blank" rel="noopener">songxuy</a></span>
        </div> -->
      </ResumeScroll>
    </div>
  </div>
  <!-- Generated By AI End (Cursor) -->
</template>

<script>
/* Generated By AI Start (Cursor) */
import ResumeIcon from '@/components/ResumeIcon.vue';
import ResumeScroll from '@/components/ResumeScroll.vue';
import headImage from '@/assets/img/head12.jpg';

export default {
  name: "partOne",
  components: { ResumeIcon, ResumeScroll },
  data() {
    return {
      headImage
    };
  }
};
/* Generated By AI End (Cursor) */
</script>

<style scoped>
/* Generated By AI Start (Cursor) */
.resume-profile-header {
  flex-shrink: 0;
  text-align: center;
}

.resume-profile-header .resume-section-title {
  justify-content: center;
  margin-bottom: 6px;
}
/* Generated By AI End (Cursor) */
</style>
