<template>
  <!-- Generated By AI Start (Cursor) -->
  <el-scrollbar class="resume-el-scrollbar">
    <slot></slot>
  </el-scrollbar>
  <!-- Generated By AI End (Cursor) -->
</template>

<script>
/* Generated By AI Start (Cursor) */
import { ElScrollbar } from 'element-plus';
import 'element-plus/es/components/scrollbar/style/css';

export default {
  name: 'ResumeScroll',
  components: { ElScrollbar }
};
/* Generated By AI End (Cursor) */
</script>

<style scoped>
/* Generated By AI Start (Cursor) */
.resume-el-scrollbar {
  flex: 1;
  min-height: 0;
  height: 100%;
}

.resume-el-scrollbar :deep(.el-scrollbar__wrap) {
  overflow-x: hidden;
}

.resume-el-scrollbar :deep(.el-scrollbar__view) {
  padding-right: 2px;
}

.resume-el-scrollbar :deep(.el-scrollbar__bar.is-horizontal) {
  display: none;
}

.resume-el-scrollbar :deep(.el-scrollbar__bar) {
  opacity: 0;
  transition: opacity 0.25s ease;
}

.resume-el-scrollbar:hover :deep(.el-scrollbar__bar) {
  opacity: 1;
}

.resume-el-scrollbar :deep(.el-scrollbar__bar.is-vertical) {
  width: 4px;
  right: 1px;
}

.resume-el-scrollbar :deep(.el-scrollbar__thumb) {
  background-color: rgba(56, 189, 248, 0.45);
  border-radius: 4px;
}

.resume-el-scrollbar:hover :deep(.el-scrollbar__thumb) {
  background-color: rgba(56, 189, 248, 0.65);
}
/* Generated By AI End (Cursor) */
</style>
