/* Generated By AI Start (Cursor) */
import * as echarts from 'echarts/core';
import {
  MapChart,
  EffectScatterChart,
  PieChart,
  RadarChart
} from 'echarts/charts';
import {
  GeoComponent,
  TooltipComponent,
  TitleComponent,
  LegendComponent,
  RadarComponent
} from 'echarts/components';
import { CanvasRenderer } from 'echarts/renderers';
import chinaJson from '@/assets/map/china.json';

echarts.use([
  MapChart,
  EffectScatterChart,
  PieChart,
  RadarChart,
  GeoComponent,
  TooltipComponent,
  TitleComponent,
  LegendComponent,
  RadarComponent,
  CanvasRenderer
]);

echarts.registerMap('china', chinaJson);

export default echarts;
/* Generated By AI End (Cursor) */
