<template>
  <div class="app" id="app">
    <div class="banner">
      <div class="banner-overlay"></div>
      <div class="banner-particles">
        <span v-for="n in 20" :key="n" class="particle" :style="particleStyle(n)"></span>
      </div>
    </div>
    <!-- Generated By AI Start (Cursor) -->
    <IdleWaveOverlay :visible="showIdleWave" />
    <!-- Generated By AI End (Cursor) -->
    <div class="resume-layout">
      <div class="resume-grid">
        <div class="grid-cell grid-one">
          <router-view name="PartOne"/>
        </div>
        <div class="grid-cell grid-two">
          <router-view name="PartTwo"/>
        </div>
        <div class="grid-cell grid-three">
          <router-view name="PartThree"/>
        </div>
        <div class="grid-cell grid-four">
          <router-view name="PartFour"/>
        </div>
        <div class="grid-cell grid-five">
          <router-view name="PartFive"/>
        </div>
        <div class="grid-cell grid-six">
          <router-view name="PartSix"/>
        </div>
        <div class="grid-cell grid-seven">
          <router-view name="PartSeven"/>
        </div>
      </div>
    </div>
  </div>
</template>

<script>
/* Generated By AI Start (Cursor) */
import IdleWaveOverlay from '@/components/IdleWaveOverlay.vue';

export default {
  name: "App",
  components: { IdleWaveOverlay },
  data() {
    return {
      showIdleWave: false,
      idleTimer: null,
      idleDelay: 3000,
      motionReduced: false
    };
  },
  mounted() {
    this.motionReduced = window.matchMedia('(prefers-reduced-motion: reduce)').matches;
    if (!this.motionReduced) {
      this.bindIdleListeners();
      this.resetIdleTimer();
    }
  },
  beforeUnmount() {
    this.clearIdleTimer();
    this.unbindIdleListeners();
  },
  methods: {
    particleStyle(n) {
      const left = ((n * 17 + 13) % 100);
      const delay = ((n * 0.7) % 5).toFixed(1);
      const duration = (4 + (n % 6)).toFixed(1);
      const size = 2 + (n % 4);
      return {
        left: left + '%',
        animationDelay: delay + 's',
        animationDuration: duration + 's',
        width: size + 'px',
        height: size + 'px'
      };
    },
    bindIdleListeners() {
      this.onUserActivity = this.onUserActivity.bind(this);
      window.addEventListener('mousemove', this.onUserActivity);
      window.addEventListener('mousedown', this.onUserActivity);
      window.addEventListener('keydown', this.onUserActivity);
      window.addEventListener('wheel', this.onUserActivity, { passive: true });
      window.addEventListener('touchstart', this.onUserActivity, { passive: true });
      window.addEventListener('touchmove', this.onUserActivity, { passive: true });
    },
    unbindIdleListeners() {
      window.removeEventListener('mousemove', this.onUserActivity);
      window.removeEventListener('mousedown', this.onUserActivity);
      window.removeEventListener('keydown', this.onUserActivity);
      window.removeEventListener('wheel', this.onUserActivity);
      window.removeEventListener('touchstart', this.onUserActivity);
      window.removeEventListener('touchmove', this.onUserActivity);
    },
    onUserActivity() {
      if (this.showIdleWave) {
        this.showIdleWave = false;
      }
      this.resetIdleTimer();
    },
    resetIdleTimer() {
      this.clearIdleTimer();
      this.idleTimer = setTimeout(() => {
        this.showIdleWave = true;
      }, this.idleDelay);
    },
    clearIdleTimer() {
      if (this.idleTimer) {
        clearTimeout(this.idleTimer);
        this.idleTimer = null;
      }
    }
  }
};
/* Generated By AI End (Cursor) */
</script>

<style>
/* Generated By AI Start (Cursor) */
html,
body,
#app {
  height: 100%;
  overflow: hidden;
}

.app {
  position: relative;
  width: 100%;
  height: 100dvh;
  max-height: 100vh;
  overflow: hidden;
  color: var(--resume-text, #f1f5f9);
  font-family: 'Inter', 'PingFang SC', 'Microsoft YaHei', sans-serif;
}

.banner {
  background: url('@/assets/img/bg.jpg');
  background-size: cover;
  background-position: center;
  position: fixed;
  top: -20px;
  left: -20px;
  right: -20px;
  bottom: -20px;
  width: 105%;
  z-index: -1;
  animation: banner-move 50s infinite alternate ease-in-out;
}

.banner-overlay {
  position: absolute;
  inset: 0;
  background: linear-gradient(135deg, rgba(10, 14, 23, 0.88) 0%, rgba(15, 23, 42, 0.75) 50%, rgba(30, 27, 75, 0.65) 100%);
}

.banner-particles {
  position: absolute;
  inset: 0;
  overflow: hidden;
  pointer-events: none;
}

.particle {
  position: absolute;
  bottom: -10px;
  border-radius: 50%;
  background: rgba(56, 189, 248, 0.6);
  box-shadow: 0 0 8px rgba(56, 189, 248, 0.5);
  animation: particle-rise linear infinite;
}

.resume-layout {
  position: relative;
  z-index: 1;
  height: 100%;
  padding: 6px;
  box-sizing: border-box;
}

.resume-grid {
  display: grid;
  height: 100%;
  gap: 6px;
  grid-template-columns: minmax(0, 6fr) minmax(0, 10fr) minmax(0, 4fr) minmax(0, 4fr);
  grid-template-rows: minmax(0, 1fr) minmax(0, 1fr);
  grid-template-areas:
    "one two three three"
    "four five six seven";
}

.grid-cell {
  min-height: 0;
  min-width: 0;
  display: flex;
  flex-direction: column;
}

.grid-one { grid-area: one; }
.grid-two { grid-area: two; }
.grid-three { grid-area: three; }
.grid-four { grid-area: four; }
.grid-five { grid-area: five; }
.grid-six { grid-area: six; }
.grid-seven { grid-area: seven; }

@media (max-width: 1199px) {
  .resume-grid {
    grid-template-columns: minmax(0, 1fr) minmax(0, 1fr);
    grid-template-rows: repeat(4, minmax(0, 1fr));
    grid-template-areas:
      "one two"
      "three four"
      "five six"
      "seven seven";
  }
}

@media (max-width: 767px) {
  .resume-layout {
    padding: 4px;
  }

  .resume-grid {
    gap: 4px;
    grid-template-columns: minmax(0, 1fr) minmax(0, 1fr);
    grid-template-rows: repeat(4, minmax(0, 1fr));
    grid-template-areas:
      "one two"
      "three four"
      "five six"
      "seven seven";
  }
}

@keyframes banner-move {
  0% { background-position: 0 0; }
  100% { background-position: 100% 0; }
}

@keyframes particle-rise {
  0% {
    transform: translateY(0) scale(1);
    opacity: 0;
  }
  10% { opacity: 1; }
  90% { opacity: 0.6; }
  100% {
    transform: translateY(-100vh) scale(0.3);
    opacity: 0;
  }
}

@media (prefers-reduced-motion: reduce) {
  .banner,
  .particle {
    animation: none !important;
  }
}
/* Generated By AI End (Cursor) */
</style>
