/* Generated By AI Start (Cursor) */
import { createApp } from 'vue';
import App from './App.vue';
import router from './router';
import '@/assets/styles/reset.css';
import '@/assets/styles/resume-theme.css';

const app = createApp(App);
app.use(router);
app.mount('#app');
/* Generated By AI End (Cursor) */
